version: 2

sources:
  - name: raw
    database: ATMOSYNC_DB
    schema: PUBLIC
    tables:
      - name: RAW_SENSOR_DATA

models:
  - name: stg_sensor_data
    columns:
      - name: reading_id
        tests:
          - unique
          - not_null

      - name: container_id
        tests:
          - not_null

      - name: timestamp
        tests:
          - not_null